### PR TITLE
fix: show channel status for opening channels

### LINKED ISSUE #302: Show channel status as "Opening" instead of "Offline" if confirmations less than required confirmations
Currently it shows "Offline" in the node page.

### PR DESCRIPTION
**Pull request by reneaaron**
Fixes #302

### CODE REVIEW

File: frontend/src/screens/channels/Channels.tsx [hunk 1]
```diff
@@ -724,14 +724,28 @@ export default function Channels() {
...
+                        : channel.confirmationsRequired !== undefined &&
+                            channel.confirmations !== undefined &&
+                            channel.confirmationsRequired >
+                              channel.confirmations
+                          ? "opening"
+                          : "offline";
+                      if (channelStatus === "opening") {
+                        channelWarning = `Channel is currently being opened (${channel.confirmations} of ${channel.confirmationsRequired} confirmations)`;
+                      }
+
```
Comment (rolznz) [inline frontend/src/screens/channels/Channels.tsx:738]: Nice. Can we also set a different channel warning if the channel is offline?
```
if (channelStatus === "offline") {
                        channelWarning = "This channel is currently offline and cannot be used to send or receive payments. Please contact Alby Support for more information";
                      }
```

**Review by rolznz — APPROVED** [review]
tACK
