### PR TITLE
fix(ui): enable keyboard submission for dialogs #760

### LINKED ISSUE #760: [Accessibility] Some dialogs are not easily submitted via keyboard
Some dialogs do not use form submission so the submit button must be focused. If there was a form, the dialog can be submitted by pressing enter on any of the fields.

### LINKED ISSUE #1976: Bug: debug tools node command dialog has no scrollbar
Image

### PR DESCRIPTION
**Pull request by keshav0479**
## Description
Fixes #760
Fixes #1976

This PR improves accessibility and UX by ensuring that dialogs with input fields can be submitted using the `Enter` key. Previously, users were required to manually click the "Confirm" button.

## Changes
- Wrapped input fields and action buttons in a `<form>` element across multiple dialog components.
- Added `onSubmit` handlers to trigger the confirm action via keyboard.
- Updated "Confirm" buttons to `type="submit"`.

## Files Updated
- `ResetRoutingDataDialogContent.tsx`
- `RoutingFeeDialogContent.tsx`
- `ExecuteCustomNodeCommandDialogContent.tsx`
- `DebugTools.tsx` (Fixed `ProbeInvoice`, `ProbeKeysend`, `RefundSwap`, `GetLogs`, and `GetNetworkGraph` dialogs)

### CODE REVIEW

File: frontend/src/components/ExecuteCustomNodeCommandDialogContent.tsx [hunk 1]
```diff
@@ -60,32 +60,39 @@ export function ExecuteCustomNodeCommandDialogContent({
...
-          />
-        </AlertDialogDescription>
-      </AlertDialogHeader>
-      <AlertDialogFooter className="mt-4">
-        <AlertDialogCancel onClick={() => setCommand("")}>
-          Cancel
-        </AlertDialogCancel>
-        <AlertDialogAction onClick={executeCommand}>Execute</AlertDialogAction>
-      </AlertDialogFooter>
+      <form onSubmit={handleSubmit}>
```
Comment (rolznz) [inline frontend/src/components/ExecuteCustomNodeCommandDialogContent.tsx]: this works well but breaks the styling a bit on the dialog. There's no spacing between the submit button and the content now. Any idea how to fix it without manually adding custom spacing?

Comment (keshav0479) [reply frontend/src/components/ExecuteCustomNodeCommandDialogContent.tsx]: Ah yeah, I see what you mean - the form wrapper is eating up the grid gap.
What if I use the form attribute approach instead? So instead of wrapping everything, I just put the form around the input and link the submit button using form="form-id". That way the original AlertDialog structure stays intact and the spacing works as expected.

Let me know if that sounds good and I'll update.

Comment (rolznz) [reply frontend/src/components/ExecuteCustomNodeCommandDialogContent.tsx]: @keshav0479 nice idea, sounds good to me!

Comment (keshav0479) [reply frontend/src/components/ExecuteCustomNodeCommandDialogContent.tsx]: Updated! Now using the form attribute approach as suggested.

**Comment by keshav0479** [comment]
Thanks for the merge! And nice catch on the routing fee dialog, i couldn't verify that one locally, so i appreciate you fixing it.
