### PR TITLE
feat: add fixed float along with bitcoin maxi mode

### LINKED ISSUE #2071: Add fixed float as a way to pay for a channel and also a way to topup
Not sure if topup is good initiated from the hub, or on getalby.com. 

Example URL:

```
https://ff.io/?to=BTCLN&address=lnbc100u1p5e93p3dqqnp4q228a2ztxkwzaypvzrsh823qngmv97f2v9puwvtsadetypmutyscwpp5s7x7qwnjafceqc6dyx30vxj4lmnfjlv3w37653ez7qw70afsg74qsp5crllvfc5qcl9mcxvpv979wglecwmzn3evvvlq8cmaec6wrsk5asq9qyysgqcqzp2xqyz5vq2tldtma36vjf5v6l4cutcsqj0x45gyxqxra5ty25pwhsqweds0ey0ffk95fvxwej2q48yqq9yv9qxm8j7j4qvjkg47q2lrxkuyu587sq5lzdq7&ref=qnnjvywb
```

Simply open it in a new tab. Make sure all the properties are set correctly as in the example.

On-chain topup would be great in the hub. (Advanced -> deposit page and receive via on-chain)

Also paying OUT would be good for both lightning and on-chain.

### PR DESCRIPTION
**Pull request by im-adithya**
Fixes #2071 

## Description
Adds fixed float option and bitcoin maxi mode to disable those suggestions in settings

## Video
https://github.com/user-attachments/assets/91f02880-8095-4026-be21-9df65e926395

## Summary by CodeRabbit

* **New Features**
  * Added Bitcoin Maxi Mode toggle in Settings > Experience section to customize your interface
  * Integrated FixedFloat crypto exchange for sending, receiving, and swapping across 70+ cryptocurrencies
  * New crypto swap flow allowing users to transact with alternative cryptocurrencies

* **Improvements**
  * Enhanced UI layouts and refined text spacing throughout the app
  * Improved conditional visibility of crypto options based on user preferences

### CODE REVIEW

**Comment by rolznz** [comment]
> Should we add to http://localhost:5173/wallet/swap too? image

To keep it simple, we could redirect to http://localhost:5173/wallet/receive/onchain with "Other Cryptocurrency" selected

**Comment by rolznz** [comment]
> image
> @im-adithya weird bug

Ah, it's not a bug. I didn't read the warning above. I should have selected "To On-Chain balance"

File: frontend/src/screens/wallet/receive/ReceiveOnchain.tsx [hunk 1]
```diff
@@ -316,62 +382,263 @@ function ReceiveToSpending() {
...
+  paymentDone: boolean;
+  onReset: () => void;
+}) {
+  if (!transaction) {
+    return (
+      <>
+        <div className="border-t pt-4 text-sm grid gap-2">
+          <div className="flex items-center justify-between">
+            <Label>Swap Fee</Label>
+            <p className="text-muted-foreground">0.5%-1% + on-chain fees</p>
```
Comment (rolznz) [inline frontend/src/screens/wallet/receive/ReceiveOnchain.tsx]: this should be 1% because to lightning we have to use the fixed option

File: frontend/src/components/CryptoSwapAlert.tsx [hunk 2]
```diff
@@ -0,0 +1,39 @@
...
+        <CoinsIcon className="h-4 w-4" />
+        Looking to pay to other Cryptocurrency?
+      </AlertTitle>
+      <AlertDescription className="text-xs gap-2 mt-1">
+        <p>
+          If you are trying to pay a non-Bitcoin payment destination, use
+          FixedFloat to swap and complete the payment across 70+ supported
+          cryptocurrencies.
+        </p>
+        <ExternalLinkButton
```
Comment (rolznz) [inline frontend/src/components/CryptoSwapAlert.tsx]: For a future integration maybe it would be cool to inject the address into the link, but it only works if `to` is provided (so the user would need to enter the currency e.g. `SOL`)

Comment (rolznz) [reply frontend/src/components/CryptoSwapAlert.tsx]: I guess doing a proper full integration at that point would be better though, I'll resolve this for now

File: frontend/src/screens/settings/Settings.tsx [hunk 3]
```diff
@@ -220,6 +223,30 @@ function Settings() {
             </div>
           </div>
         </div>
+
+        <div className="space-y-4">
+          <h3 className="text-xl font-medium">Experience</h3>
+          <div className="flex items-center justify-between max-w-md rounded-lg border p-3">
+            <div className="grid gap-2">
+              <Label htmlFor="bitcoin-maxi-mode">Bitcoin Maxi mode</Label>
```
Comment (rolznz) [inline frontend/src/screens/settings/Settings.tsx:239]: should we add a followup issue for "Hide fiat"? as another option inside this maxi mode section?

Comment (im-adithya) [reply frontend/src/screens/settings/Settings.tsx:239]: Opened #2101

File: frontend/src/hooks/useBitcoinMaxiMode.ts [hunk 4]
```diff
@@ -0,0 +1,18 @@
+import React from "react";
+import { localStorageKeys } from "src/constants";
+
+export function useBitcoinMaxiMode() {
+  const [bitcoinMaxiMode, setBitcoinMaxiModeState] = React.useState<boolean>(
+    localStorage.getItem(localStorageKeys.bitcoinMaxiMode) === "true"
```
Comment (rolznz) [inline frontend/src/hooks/useBitcoinMaxiMode.ts]: This is inconsistent with our other settings, which are stored in the DB.

Comment (im-adithya) [reply frontend/src/hooks/useBitcoinMaxiMode.ts]: Yeah I was thinking about this, would be almost the same effort to implement it on the backend, but I went with it as discussed in our call. Should we change (I vote yes)?

File: frontend/src/components/CryptoSwapAlert.tsx [hunk 5]
```diff
@@ -0,0 +1,39 @@
...
+          to="https://ff.io/?ref=qnnjvywb&from=BTCLN"
```
Comment (rolznz) [inline frontend/src/components/CryptoSwapAlert.tsx]: can you DRY link creation up? let's have the link + ref code in a single util function. Right now it's spread across 5 files

Comment (rolznz) [reply frontend/src/components/CryptoSwapAlert.tsx]: Or extract to a "FixedFloatButton" or something

File: frontend/src/hooks/useBitcoinMaxiMode.ts (hunk 4 above)
Comment (rolznz) [reply frontend/src/hooks/useBitcoinMaxiMode.ts]: Since it is basically same effort, I think being consistent is good, so I would vote yes too

File: frontend/src/constants.ts [hunk 6]
```diff
@@ -4,11 +4,13 @@ export const localStorageKeys = {
   channelOrder: "channelOrder",
   authToken: "authToken",
   supportAlbySidebarHintHiddenUntil: "supportAlbySidebarHintHiddenUntil",
+  bitcoinMaxiMode: "bitcoinMaxiMode",
 };
 
 export const ONCHAIN_DUST_SATS = 1000;
 export const ALBY_HIDE_HOSTED_BALANCE_BELOW = 100;
 export const ALBY_MIN_HOSTED_BALANCE_FOR_FIRST_CHANNEL = 10_000;
+export const FIXED_FLOAT_MIN_SWAP_AMOUNT = 20000;
```
Comment (rolznz) [inline frontend/src/constants.ts]: I don't think we should have this, we have no control over this amount do we? and doesn't it depend on the swapping pairs? like SOL can go way lower

**Comment by rolznz** [comment]
> Hmmm I was thinking to do that once we have a proper fixed float swap service running in the backend, but yeah it makes sense to add it in swaps as more people might find out 👍

@im-adithya you didn't do this yet, right?

File: frontend/src/components/CryptoSwapAlert.tsx (hunk 5 above)
Comment (im-adithya) [reply frontend/src/components/CryptoSwapAlert.tsx]: Done ✅

File: frontend/src/hooks/useBitcoinMaxiMode.ts (hunk 4 above)
Comment (im-adithya) [reply frontend/src/hooks/useBitcoinMaxiMode.ts]: Done ✅

File: frontend/src/screens/wallet/swap/index.tsx [hunk 7]
```diff
@@ -133,135 +166,182 @@ function SwapInForm() {
...
+              placeholder="Amount in satoshis"
+              value={swapAmount}
+              min={swapFrom !== "crypto" ? swapInfo.minAmount : undefined}
+              max={Math.min(
+                swapInfo.maxAmount,
+                ...(isInternalSwap
+                  ? [spendableOnchainBalanceWithAnchorReserves]
+                  : []),
+                (balances.lightning.totalReceivable / 1000) * 0.99
+              )}
```
[the remark this answers is not in the document]
Comment (im-adithya) [reply frontend/src/screens/wallet/swap/index.tsx]: Done!

File: frontend/src/screens/wallet/receive/ReceiveOnchain.tsx [hunk 8]
```diff
@@ -316,62 +372,144 @@ function ReceiveToSpending() {
...
+            <InputWithAdornment
+              type="number"
+              autoFocus
+              placeholder="Amount in satoshis"
+              value={swapAmount}
+              min={swapFrom === "bitcoin" ? swapInfo.minAmount : undefined}
+              max={Math.min(
+                swapInfo.maxAmount,
+                (balances.lightning.totalReceivable / 1000) * 0.99
+              )}
```
[the remark this answers is not in the document]
Comment (im-adithya) [reply frontend/src/screens/wallet/receive/ReceiveOnchain.tsx]: Done!

File: frontend/src/components/FixedFloatSwapInFlow.tsx [hunk 9]
```diff
@@ -0,0 +1,155 @@
...
+    true
+  );
+  const [paymentDone, setPaymentDone] = useState(false);
+
+  useEffect(() => {
+    if (invoiceData?.settledAt) {
+      // eslint-disable-next-line react-hooks/set-state-in-effect
+      setPaymentDone(true);
+    }
+  }, [invoiceData]);
```
[the remark this answers is not in the document]
Comment (im-adithya) [reply frontend/src/components/FixedFloatSwapInFlow.tsx:51]: Thanks for catching, fixed!
