### PR TITLE
fix: prevent QR code from opening blank tabs and add click-to-reveal

### LINKED ISSUE #487: Clicking hub new connection QR code opens blank tab
"When adding a new connection in Alby Hub when on the "Reveal QR" screen with the blurred QR code if you click on the blurred background image of the QR it opens a new blank tab. 

After revealing the QR code clicking on the QR code itself will open another blank tab. 

I would expect that clicking on the blurred QR the first time would reveal it and once the QR is revealed the QR code would either be unclickable or clicking on the QR code would copy the pairing secret."

Source: https://feedback.getalby.com/-report-a-bug-1/posts/clicking-hub-new-connection-qr-code-opens-blank-tab

### PR DESCRIPTION
**Pull request by Aditya-PS-05**
closes #487 

## Changes:
Now when user clicks on the qr-code, it won't navigate to the blank page (issue was with `<a>` tag) and when user clicks on either on the blurred qr image or reveal qr button, the qr will be revealed. But user need to click on the "copy" button to copy the pairing secret.

### CODE REVIEW

File: frontend/src/screens/apps/AppCreated.tsx [hunk 1]
```diff
@@ -192,8 +192,13 @@ export function ConnectAppCard({
             <p>App connected</p>
           </Badge>
         )}
-        <a href={pairingUri} target="_blank" className="relative">
-          <div className={!isQRCodeVisible ? "blur-md" : ""}>
+        <div className="relative">
+          <div
+            className={`${!isQRCodeVisible ? "blur-md cursor-pointer" : ""}`}
```
Comment (rolznz) [inline frontend/src/screens/apps/AppCreated.tsx]: You can use the `cn` util and just do `!isQRCodeVisible &&` instead of a ternary operator (see elsewhere)

File: frontend/src/screens/apps/AppCreated.tsx [hunk 2]
```diff
@@ -192,8 +192,13 @@ export function ConnectAppCard({
...
+            onClick={
+              !isQRCodeVisible ? () => setIsQRCodeVisible(true) : undefined
```
Comment (rolznz) [inline frontend/src/screens/apps/AppCreated.tsx]:
```suggestion
              () => setIsQRCodeVisible(true)
```
is simpler
