### PR TITLE
fix: prevent LN client access during shutdown

### LINKED ISSUE #2018: Disable node-related API endpoints when node is shutting down
I noticed it's possible (and a crash can happen) when the node is shutting down. e.g. if someone presses the shutdown button and then tries to connect a peer.

Normally shutdown is fast but sometimes it's delayed by a node sync or other node-related required actions.

### PR DESCRIPTION
**Pull request by im-adithya**
Fixes #2018

## Summary by CodeRabbit

* **Bug Fixes**
  * Better handling when the Lightning node client is unavailable — prevents failures during account linking, automated channel requests, and OAuth callback processing.
  * Improved shutdown sequence for the Lightning node client to ensure cleaner termination and fewer transient errors.

* **Refactor**
  * Reduced repeated node-client lookups by reusing a single client per request, simplifying control flow and increasing stability.

### CODE REVIEW

File: service/start.go [hunk 1]
```diff
@@ -327,7 +327,9 @@ func (svc *service) launchLNBackend(ctx context.Context, encryptionKey string) e
 	go func() {
 		// ensure the LNClient is stopped properly before exiting
 		<-ctx.Done()
+		svc.lnClientShuttingDown = true
```
Comment (rolznz) [inline service/start.go]: can updating this boolean go inside the stopLNClient() method?

File: service/start.go [hunk 2]
```diff
@@ -327,7 +327,9 @@ func (svc *service) launchLNBackend(ctx context.Context, encryptionKey string) e
...
 		svc.stopLNClient()
+		svc.lnClientShuttingDown = false
```
Comment (rolznz) [inline service/start.go]: this one could be in the defer func of stopLNClient

File: service/stop.go [hunk 3]
```diff
@@ -17,7 +17,12 @@ func (svc *service) StopApp() {
 }
 
 func (svc *service) stopLNClient() {
-	defer svc.wg.Done()
+	svc.lnClientShuttingDown = true
+	defer func() {
+		svc.lnClientShuttingDown = false
+		svc.wg.Done()
+	}()
```
[the remark this answers is not in the document]
Comment (im-adithya) [reply service/stop.go]: @rolznz this `atomic.Bool` solution looks good, should we use it?
