### PR TITLE
fix: unlock error when node is not started

### LINKED ISSUE #2118: Bug: confusing error message when calling unlock if the node isn't started
Currently it says "Failed to save session: config not unlocked"

### PR DESCRIPTION
**Pull request by im-adithya**
Fixes #2118

## Summary by CodeRabbit

* **New Features**
  * Unlock flow now checks node status before completing unlock; successful unlocks behave as before.

* **Bug Fixes**
  * More consistent and clearer error responses when the node is not running or its status cannot be retrieved.

* **Tests**
  * Added tests for the node-not-running unlock case and updated related tests to use a mocked node status.

### CODE REVIEW

File: http/http_service.go [hunk 1]
```diff
@@ -346,8 +346,14 @@ func (httpSvc *HttpService) unlockHandler(c echo.Context) error {
 		})
 	}
 
-	token, err := httpSvc.createJWT(unlockRequest.TokenExpiryDays, unlockRequest.Permission)
+	_, err := httpSvc.api.GetNodeStatus(c.Request().Context())
+	if err != nil {
+		return c.JSON(http.StatusBadRequest, ErrorResponse{
```
Comment (rolznz) [inline http/http_service.go]: is it OK to assume this is the reason for the error always? can we check the error type?

Comment (im-adithya) [reply http/http_service.go]: Fixed ✅
