### PR TITLE
fix: use workdir for temp bkp file

### LINKED ISSUE #391: Restore backup on Mac Desktop does not work
image

### PR DESCRIPTION
**Pull request by im-adithya**
Fixes #391

I failed to see the "failed to create decrypted reader" error as shown in the issue comment, but it should be good as I tested it twice (and saw only the below issue)

This PR solves the issue which gives the "failed to create temporary output file: operation not permitted" error because the directory being used is outside the permitted directory

## Tests

- [x] HTTP - Wails
- [x] HTTP - HTTP
- [x] Wails - HTTP
- [x] Wails - Wails

### CODE REVIEW

File: api/backup.go [hunk 1]
```diff
@@ -148,7 +148,7 @@ func (api *api) RestoreBackup(unlockPassword string, r io.Reader) error {
 		return fmt.Errorf("failed to create decrypted reader: %w", err)
 	}
 
-	tmpF, err := os.CreateTemp("", "nwc-*.bkp")
+	tmpF, err := os.CreateTemp(api.cfg.GetEnv().Workdir, "nwc-*.bkp")
```
Comment (bumi) [inline api/backup.go:151]: should the file be renamed to `albyhub-` ?

and maybe we can make a sub directory?

File: .github/workflows/wails.yml [hunk 2]
```diff
@@ -200,7 +200,7 @@ jobs:
           mv ./build/out/${{ env.PACKAGE_NAME }}.dmg ./build/bin/
 
       - name: Notarize the DMG image
-        if: runner.os == 'macOS' && inputs.build-release
+        if: runner.os == 'macOS'
```
Comment (rolznz) [inline .github/workflows/wails.yml:203]: was this intentional?

Comment (im-adithya) [reply .github/workflows/wails.yml:203]: Yes, we have to notarize this everytime, otherwise only signing wouldn't work (unless you already opened the app before) And we have a limit of 70 notarizations per day (with our apple dev account) so this should be good atleast for now

File: api/backup.go (hunk 1 above)
Comment (im-adithya) [reply api/backup.go:151]: Yes I wanted to change this to albyhub- as well, also the backup file. But would it have any side effects? cc @rolznz

File: .github/workflows/wails.yml (hunk 2 above)
Comment (rolznz) [reply .github/workflows/wails.yml:203]: @im-adithya but people only run the release builds, don't they?

File: api/backup.go (hunk 1 above)
Comment (rolznz) [reply api/backup.go:151]: aren't you creating a brand new folder? why are there side effects?

Comment (rolznz) [reply api/backup.go:151]: Oh. This temp file is only used in this backup process. So if you rename it here, just check it is not used elsewhere

File: .github/workflows/wails.yml (hunk 2 above)
Comment (im-adithya) [reply .github/workflows/wails.yml:203]: Yeah but I thought if someone of us is testing for the first time, they might see this issue. But on second thoughts it might hit the 70 limit someday and might create problem during release, I'll add this back 👍

**Comment by rolznz** [comment]
@im-adithya what tests did you do for this?

>  but it should be good as I tested it twice (and saw only the below issue)

what was the issue?

**Comment by im-adithya** [comment]
> what was the issue?

I was referring to the screenshot you posted in #391

`failed to read salt: EOF`

But it is an old version so i think this fix should solve the problem

File: api/backup.go (hunk 1 above)
Comment (rolznz) [reply api/backup.go:151]: @im-adithya you didn't rename the file?

**Comment by rolznz** [comment]
@im-adithya can you re-review your code and test it again

**Review by rolznz — APPROVED** [review]
tACK (Linux)
