### PR TITLE
fix: Remove balance check from auto-swap limit

### LINKED ISSUE #1822: Remove spending balance requirement for setting up auto-swaps
When I set up an auto-swap it checks my current spending balance. Low spending balances  basically prevent users from setting up future auto-swaps.
Can we remove this requirement? 

Image

### PR DESCRIPTION
**Pull request by Dunsin-cyber**
Fixes #1822

Another thing worth considering is a potential logic flaw I've identified. Presently, there is no validation to ensure the `Spending balance threshold` is greater than or equal to the `Swap amount`.

This allows a user to create a configuration that will always fail. For example:

1.  Set **Balance Threshold** to `10,000` sats.
2.  Set **Swap Amount** to `25,000` sats.

The system will trigger the swap when the Lightning balance reaches 10,000 sats, but the action to swap 25,000 sats will immediately fail due to insufficient funds. This could lead to a confusing user experience with perpetually failing transactions.

**Suggestion:**
We should add a validation rule to the form that prevents saving if the `Swap amount` is greater than the `Balance threshold`.

### CODE REVIEW

**Comment by Dunsin-cyber** [comment]
> @Dunsin-cyber I think that's a good suggestion. Would you like to add it in this PR?

alright, on it.

File: http/http_service.go [hunk 1]
```diff
@@ -1510,6 +1510,12 @@ func (httpSvc *HttpService) enableAutoSwapOutHandler(c echo.Context) error {
 		})
 	}
 
+	if enableAutoSwapRequest.SwapAmount > enableAutoSwapRequest.BalanceThreshold {
```
Comment (rolznz) [inline http/http_service.go]: This won't apply in the wails / desktop app. We could move it to the API layer but I think it's fine just to do the check in the frontend in the `onSubmit` function.

Comment (Dunsin-cyber) [reply http/http_service.go]: alright.
okay, then, i'd limit the check to just the frontend

Comment (Dunsin-cyber) [reply http/http_service.go]: done

**Review by rolznz — APPROVED** [review]
utACK
