### PR TITLE
fix: sidebar accessibility and double tabbed responsive buttons

### LINKED ISSUE #1775: (Accessibility) sidebar menu items get focused twice when tabbing
You have to press tab twice for each menu item.

In the console we also get this error which might be related and should be fixed:
`Warning: validateDOMNesting(...): <button> cannot appear as a descendant of <button>.`

Image

### PR DESCRIPTION
**Pull request by krrish-sehgal**
fixes #1775

1. Sidebar Navigation Issue
Problem: Nested interactive elements ``NavLink`` wrapping ``SidebarMenuButton`` caused double tab navigation and DOM validation errors
Solution: Used ``asChild`` pattern to make ``SidebarMenuButton`` render as ``NavLink`` instead of nesting them, eliminating duplicate focusable elements

2. Add Connection Button Issue
Problem: ``Link`` wrapping ``ResponsiveButton`` created nested anchor/button elements, requiring double tab presses to focus
Solution: Replaced with ``Button asChild`` containing ``Link`` to merge button styling with link behavior into single focusable element

https://github.com/user-attachments/assets/5cd32f91-1ff7-42b7-8dd8-b3cd647acd23

### CODE REVIEW

File: frontend/src/components/AppSidebar.tsx [hunk 1]
```diff
@@ -136,20 +136,20 @@ export function AppSidebar() {
           <SidebarGroupContent>
             <SidebarMenu>
               {data.navMain.map((item) => (
-                <NavLink key={item.title} to={item.url} end>
-                  {({ isActive }) => (
```
Comment (rolznz) [inline frontend/src/components/AppSidebar.tsx:141]: Why did you remove `isActive`? this is important as it highlights the current page on the sidebar

Comment (krrish-sehgal) [reply frontend/src/components/AppSidebar.tsx:141]: i'll check!

@rolznz , that's my bad, missed it there..
I have fixed it 

Screenshot 2025-10-18 at 1 47 06 AM

Comment (krrish-sehgal) [reply frontend/src/components/AppSidebar.tsx:141]: fixed!

**Comment by rolznz** [comment]
@krrish-sehgal can you test it again? I still get two focuses per sidebar item.

**Comment by krrish-sehgal** [comment]
@rolznz , its fixed: 

https://github.com/user-attachments/assets/24b73d67-a3fd-48d2-a530-ee36cf184d87


Now, I Used the render props pattern from NavLink to access isActive state, then
pass it to SidebarMenuButton with asChild prop. The asChild prop makes
SidebarMenuButton render its children (a span) with all the button styling
and data attributes, but the NavLink wrapper remains the only focusable
element.

File: frontend/src/screens/apps/Connections.tsx [hunk 2]
```diff
@@ -30,9 +30,17 @@ export function Connections() {
         title="Connections"
         contentRight={
           <>
-            <Link to="/apps/new">
-              <ResponsiveButton icon={CirclePlusIcon} text="Add Connection" />
```
Comment (rolznz) [inline frontend/src/screens/apps/Connections.tsx:34]: Please undo this change and consider another way

File: frontend/src/components/AppSidebar.tsx [hunk 3]
```diff
@@ -167,8 +169,8 @@ export function AppSidebar() {
         <SidebarMenu>
           <SidebarMenuItem>
             <DropdownMenu>
-              <DropdownMenuTrigger className="w-full">
-                <SidebarMenuButton size="lg">
+              <SidebarMenuButton size="lg" asChild>
```
Comment (rolznz) [inline frontend/src/components/AppSidebar.tsx:174]: The "Alby Account Settings" does not work when tabbing to it and pressing enter, could you have a look? and please double-check / test that all the links, menu items etc. work with your changes

Comment (im-adithya) [reply frontend/src/components/AppSidebar.tsx:174]: I don't think we can't make this work, the tabbing doesn't work in here too: https://ui.shadcn.com/docs/components/dropdown-menu

Comment (rolznz) [reply frontend/src/components/AppSidebar.tsx:174]: @im-adithya arrow keys work, so it's still accessible via keyboard at least.

Comment (rolznz) [reply frontend/src/components/AppSidebar.tsx:174]: Did you get it working? is the PR ready for re-review?

Comment (im-adithya) [reply frontend/src/components/AppSidebar.tsx:174]: Yes the sidebar is ready, but I noticed that there are a lot of places where the Button is wrapped in a Link or External Link which is causing double tabbing (I've covered 3/4th of it locally but the list is too long), should we limit this PR to the Sidebar?

Comment (rolznz) [reply frontend/src/components/AppSidebar.tsx:174]: @im-adithya sounds good :pray:

Comment (rolznz) [reply frontend/src/components/AppSidebar.tsx:174]: @im-adithya not sure how you tested it but some sidebar items are still focused twice and the alby account link in the dropdown menu doesn't work. I will fix it.

Comment (rolznz) [reply frontend/src/components/AppSidebar.tsx:174]: With `modal={false}` on the dropdown menu, in mobile the buttons aren't working and content underneath is being selected instead, do you remember why you added it?

File: frontend/src/screens/apps/Connections.tsx (hunk 2 above)
Comment (rolznz) [reply frontend/src/screens/apps/Connections.tsx:34]: Undid this change and still tab only happens once. I'm not sure why this was done

Comment (rolznz) [reply frontend/src/screens/apps/Connections.tsx:34]: EDIT: I added responsive link button classes.

File: frontend/src/components/AppSidebar.tsx (hunk 3 above)
Comment (rolznz) [reply frontend/src/components/AppSidebar.tsx:174]: Added new follow-up issue for other places in the app: https://github.com/getAlby/hub/pull/1786

Comment (im-adithya) [reply frontend/src/components/AppSidebar.tsx:174]: I added `modal={false}` to try if that helps with the tabbing as suggested [here](https://github.com/shadcn-ui/ui/discussions/2915) but it didn't help, left it as I thought selecting content underneath is good, but on second thoughtI think it's better to remove the modal first on clicking outside :+1:

Comment (rolznz) [reply frontend/src/components/AppSidebar.tsx:174]: The problem I had on mobile was if I click on the modal item (Alby Account Link) it instead opened the "Review and Earn" button from the sidebar which was behind the modal. This was on chrome devtools, not sure if it's an issue on a real mobile device, but a bit worrying anyway

Comment (im-adithya) [reply frontend/src/components/AppSidebar.tsx:174]: Ah, best to leave it as is then
