### PR TITLE
fix: remove lnd certificate from user config if not provided

### LINKED ISSUE #405: Bug: Self-signed LND certificates error in Windows Desktop
From https://primal.net/e/note16l86pvcfcqdkrpm7h0re58gn9420js2tszndxqh08xfgvqe2lxpqph82r0

> (1) There seems to be an issue when LND uses self-signed certificates, which is the default behavior. AlbyHub complains that the certificate isn't trusted, and this happens even if the self-signed certificate is added to the Trusted Root Authorities folder in the Windows Certs console. What I ended up doing was creating a dedicated DNS entry for LND (lnd.mydomain.com), and then getting a free SSL cert from one of the countless free providers, including that DNS name on the certificate. I forced LND to use that certificate instead of the self-signed one and then referenced it in the AlbyHub setup. That seemed to clear up the error.

### PR DESCRIPTION
**Pull request by im-adithya**
Fixes #405

### CODE REVIEW

File: config/config.go [hunk 1]
```diff
@@ -71,6 +71,12 @@ func (cfg *config) init(env *AppConfig) error {
 		if err != nil {
 			return err
 		}
+	} else {
+		// If no LNDCertFile is provided, we create a new one during startup
```
Comment (rolznz) [inline config/config.go:75]: what do you mean by "create a new one"? this comment seems incorrect to me

**Review by rolznz — APPROVED** [review]
utACK (once comment is fixed)

File: config/config.go (hunk 1 above)
Comment (rolznz) [reply config/config.go:75]: This is a bit ungraceful - now all users even ones who do not run LND will have this entry in their user config

Comment (rolznz) [reply config/config.go:75]: should we only run that code if `cfg.Env.LNBackendType` is LND?

Comment (im-adithya) [reply config/config.go]: I think the comment is misleading, it just skips the tls verification if no certificate is provided. And for that to happen, we need to leave this empty. So other backends should be fine.

**Review by rolznz — APPROVED** [review]
tACK
