### PR TITLE
fix: use local instead of guess

### LINKED ISSUE #1122: the wallet view page panics because of timezone
Source of the report: https://feedback.getalby.com/-report-a-bug-1/posts/the-wallet-view-page-panics-because-of-timezone

> Unexpected Application Error!
Invalid time zone specified: Etc/Unknown
RangeError: Invalid time zone specified: Etc/Unknown
at Date.toLocaleString (<anonymous>)
at lt.tz (https://my.albyhub.com/assets/index-zkNT2AwI.js:2608:320329)
at TransactionItem (https://my.albyhub.com/assets/index-zkNT2AwI.js:2608:428964)
at Xh (https://my.albyhub.com/assets/index-zkNT2AwI.js:38:21311)
at Wk (https://my.albyhub.com/assets/index-zkNT2AwI.js:40:47706)
at Vk (https://my.albyhub.com/assets/index-zkNT2AwI.js:40:43081)
at Uk (https://my.albyhub.com/assets/index-zkNT2AwI.js:40:43005)
at Jk (https://my.albyhub.com/assets/index-zkNT2AwI.js:40:42846)
at Ok (https://my.albyhub.com/assets/index-zkNT2AwI.js:40:38879)
at Fk (https://my.albyhub.com/assets/index-zkNT2AwI.js:40:39753)

> please fix this, i tagged the alby account on nostr but got no response
> it should just fall back to UTC

### PR DESCRIPTION
**Pull request by im-adithya**
Fixes #1122

~Taken from: https://github.com/iamkun/dayjs/issues/2560#issuecomment-2247454893~ We thought replacing guess with local is better than using a hacky conditional.

### CODE REVIEW

File: frontend/src/components/TransactionItem.tsx [hunk 1]
```diff
@@ -212,7 +212,11 @@ function TransactionItem({ tx }: Props) {
               <p>Date & Time</p>
               <p className="text-muted-foreground">
                 {dayjs(tx.updatedAt)
-                  .tz(dayjs.tz.guess())
+                  .tz(
```
Comment (rolznz) [inline frontend/src/components/TransactionItem.tsx:215]: Is this really the only place there is an issue despite using dayjs everywhere?

To me this feels like a hack. What about using `local`? https://day.js.org/docs/en/manipulate/local

**Comment by mleku** [comment]
https://images.mleku.dev/1memes/doit.gif

File: frontend/src/components/TransactionItem.tsx (hunk 1 above)
Comment (im-adithya) [reply frontend/src/components/TransactionItem.tsx]: Yeah the problem is only with the `guess` function, updated to use `local` instead.

**Review by rolznz — APPROVED** [review]
utACK
