### PR TITLE
fix: support alby

### LINKED ISSUE #1260: Revert v4v step from onboarding checklist & introduce other prompts to support
- [ ] revert v4v step from onboarding list
- [ ] add notification box once a month
- [ ] improvements to Support Alby Hub UI

[Figma file](https://www.figma.com/design/2IyilDewDrdNP3G1NixPYd/%F0%9F%8C%93-Alby-Hub?node-id=8225-171739&t=LswV20hWUz5TWAEY-4)

Image

Image

### PR DESCRIPTION
**Pull request by reneaaron**
Fixes #1260 

## TODO
 - [x] Display prompt in sidebar on 21st of month
 - [x] Button alignment on support-alby page

### CODE REVIEW

File: frontend/src/components/SidebarHint.tsx [hunk 1]
```diff
@@ -9,13 +15,25 @@ import {
...
+  const { data: apps } = useApps();
+  const { data: albyMe } = useAlbyMe();
   const { order } = useChannelOrderStore();
   const location = useLocation();
+  const { toast } = useToast();
+
+  const SUPPORT_CARD_KEY_HIDDEN_UNTIL = "supporter-card-hidden";
+  const [hiddenUntil, setHiddenUntil] = React.useState(
+    localStorage.getItem(SUPPORT_CARD_KEY_HIDDEN_UNTIL)
+  );
```
Comment (im-adithya) [inline frontend/src/components/SidebarHint.tsx:36]: Can we add this to `localStorageKeys` in `frontend/src/constants.ts`

File: frontend/src/screens/alby/SupportAlby.tsx [hunk 2]
```diff
@@ -155,208 +156,187 @@ function SupportAlby() {
...
+          </CardHeader>
+          <CardFooter className="flex justify-end">
+            <UpgradeDialog>
+              <Button>
+                <Sparkles className="w-4 h-4 mr-2" />
+                Upgrade to Pro
+              </Button>
+            </UpgradeDialog>
+          </CardFooter>
+        </Card>
```
Comment (im-adithya) [inline frontend/src/screens/alby/SupportAlby.tsx:181]: We show this even when the user is subscribed to Pro, I check if we don't redirect but even in the sidebar there's no check to see if they are already subscribed

Comment (reneaaron) [reply frontend/src/screens/alby/SupportAlby.tsx:181]: In the sidebar there is a check: 

https://github.com/getAlby/hub//blob/d4bf1cddf53229ca144162dde7a28ae667d8d9de/frontend/src/components/SidebarHint.tsx#L88-L91

Comment (im-adithya) [reply frontend/src/screens/alby/SupportAlby.tsx:181]: Ah sorry missed that :+1:

**Review by im-adithya — APPROVED** [review]
tACK
